---
title: "ESM203Assignment4"
author: "Madeline Gorchels"
date: "12/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE} 
#package and df loading code chunk

library(tidyverse)
library(knitr)
library(kableExtra)

```


```{r, include=FALSE}
#Defining variables 
high_tide = 2.5
low_tide = -2.5
sea_sd = 3

meter_in_conv = 0.0254

low_est_2020 = 2*meter_in_conv
low_est_2050 = 7*meter_in_conv

mid_25_2020 = 4*meter_in_conv
mid_75_2020 = 8*meter_in_conv

mid_25_2050 = 11*meter_in_conv
mid_75_2050 = 24*meter_in_conv

high_est_2020 = 11*meter_in_conv
high_est_2050 = 31*meter_in_conv
```


```{r, echo=FALSE}

#creating a dataframe with all the probabilities 

prob_df = data.frame(year = c(2018, 2020, 2050, 2020, 2050, 2020, 2050, 2020, 2050), 
                     percentile = c("NA", "10th percentile","10th percentile","25th percentile","25th percentile","75th percentile","75th percentile","90th percentile","90th percentile"),
                     sea_level_rise = c(0, low_est_2020, low_est_2050, mid_25_2020, mid_25_2050,  0.2032, mid_75_2050, 11*meter_in_conv, high_est_2050),
                     probablity_high_tide = (pnorm(5, mean =prob_df$sea_level_rise+high_tide, sd = sea_sd, lower.tail = FALSE)),
                     probablity_low_tide = (pnorm(5, mean =prob_df$sea_level_rise+low_tide, sd = sea_sd, lower.tail = FALSE)),
                     probablity_high_tide_one = (pnorm(5, mean =prob_df$sea_level_rise+high_tide+1, sd = sea_sd, lower.tail = FALSE)),
                     probablity_low_tide_one = (pnorm(5, mean =prob_df$sea_level_rise+low_tide+1, sd = sea_sd, lower.tail = FALSE)),
                     probablity_high_tide_two = (pnorm(5, mean =prob_df$sea_level_rise+high_tide+2, sd = sea_sd, lower.tail = FALSE)),
                     probablity_low_tide_two = (pnorm(5, mean =prob_df$sea_level_rise+low_tide+2, sd = sea_sd, lower.tail = FALSE)),
                      probablity_high_tide_three = (pnorm(5, mean =prob_df$sea_level_rise+high_tide+3, sd = sea_sd, lower.tail = FALSE)),
                     probablity_low_tide_three = (pnorm(5, mean =prob_df$sea_level_rise+low_tide+3, sd = sea_sd, lower.tail = FALSE))) 


```


```{r, include=FALSE}
#creating an 2020 only dataframe

prob_2020 = tidy_prob %>% 
  filter(year == 2020)

prob_2050 = tidy_prob %>% 
  filter(year == 2050)

prob_2020_low = prob_2020 %>% 
  filter(tide == "low")

prob_2050_low = prob_2050 %>% 
  filter(year == "low")

prob_2020_high = prob_2020 %>% 
  filter(tide == "high")

prob_2050_high = prob_2050 %>% 
  filter(tide == "high")
```

```{r, include=FALSE}
#I used excel to put the information in prob_df in tidy format. Then I subtracted the probability with no climate change from each value. The probabilty tab shows increase in probability from the baseline scenario. 

tidy_prob = read_csv("NYCflooding.csv") %>% 
  select(-X7,-X8,-X9) %>% 
  mutate(percent_num = case_when(
    percentile == "10th percentile"~10, 
    percentile == "25th percentile"~25,
    percentile == "75th percentile"~75,
    percentile == "90th percentile"~90)) %>% 
  group_by(storm_surge)

```


```{r, include=FALSE}
tidy_fig_2020 = ggplot(prob_2020_high, aes(x = percent_num, y = probabilty_flood), group_by(storm_surge))+
  geom_point(aes(color = storm_surge, shape = percentile))+
  theme_classic()+
  labs(x = "Sea Level Rise Projection Percentile", y = "Increased Probabilty of Flood")

tidy_fig_2020
```

```{r, include=FALSE}

tidy_fig_2050 = ggplot(prob_2050_high, aes(x = percent_num, y = probabilty_flood), group_by(storm_surge))+
  geom_point(aes(color = storm_surge, shape = percentile))+
  theme_classic()+
  labs(x = "Sea Level Rise Projection Percentile", y = "Increased Probabilty of Flood")

tidy_fig_2050
```

```{r}
tidy_fig_2020 = ggplot(prob_2020, aes(x = percent_num, y = probabilty_flood), group_by(storm_surge))+
  geom_point(aes(color = storm_surge, shape = tide))+
  theme_classic()+
  labs(x = "Sea Level Rise Projection Percentile", y = "Increased Probabilty of Flood", color = "Storm Surge (m)\n", shape = "Tide\n")+
  scale_shape_manual(labels = c("High", "Low"), values = c("circle", "triangle"))+
  scale_y_continuous(expand = c(0.01,0), limits = c(0, 0.05))+
  scale_x_continuous(expand = c(0,10))
  

tidy_fig_2020
```
```{r}
tidy_fig_2050 = ggplot(prob_2050, aes(x = percent_num, y = probabilty_flood), group_by(storm_surge))+
  geom_point(aes(color = storm_surge, shape = tide))+
  theme_classic()+
  labs(x = "Sea Level Rise Projection Percentile", y = "Increased Probabilty of Flood", color = "Storm Surge (m)\n", shape = "Tide\n")+
  scale_shape_manual(labels = c("High", "Low"), values = c("circle", "triangle"))+
  scale_y_continuous(expand = c(0.01,0), limits = c(0, 0.125))+
  scale_x_continuous(expand = c(0,10))
  

tidy_fig_2050
```

